name = "MatchPy"
uuid = "1750cefb-754d-4383-8ab7-d9c1d1688458"
version = "1.0.1-DEV"
authors = ["jverzani <jverzani@gmail.com> and contributors"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
Combinatorics = "0.7,1,1.1.0"
TermInterface = "2.0.0"
TupleTools = "1.6.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
